eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defualtZone: http://localhost:8786/eureka/
  instance:
    hostname: localhost

microservice: 
  payemnt-service: 
    endpoints: 
       endpoint: 
         uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service: 
    endpoints: 
       endpoint: 
         uri: http://ORDER-SERVICE/order/bookOrder
